### ISSUE TITLE
User Logged Test

### ISSUE THREAD

**Issue by Dejv92** [wUFr/flexi-admin#1]
Top text "logged as wUFr" is messed up on mozilla firefox 45.0.1 on ubuntu based os.
change line 8123 in generated styles to:
`
.site_header > .inside .user .logged {
    float: left;
    overflow: hidden;
    white-space: nowrap;
}`
helped me, but not tested on different browsers

![flex-admin-issue](https://cloud.githubusercontent.com/assets/7514854/15091260/741c45d6-1443-11e6-988b-d78435198afc.png)

**Comment by wUFr** [comment]
fixed - https://github.com/wUFr/flexi-admin/commit/3a59c52265cd5d2cb7ef7aebc6db465fe7696664

thx :D :dancers:
